# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1110, 556)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 200, 101, 16))
        self.label_5.setObjectName("label_5")
        self.lneBschreibung = QtWidgets.QLineEdit(self.centralwidget)
        self.lneBschreibung.setGeometry(QtCore.QRect(40, 220, 261, 161))
        self.lneBschreibung.setText("")
        self.lneBschreibung.setObjectName("lneBschreibung")
        self.tblGros = QtWidgets.QTableWidget(self.centralwidget)
        self.tblGros.setGeometry(QtCore.QRect(311, 50, 741, 401))
        self.tblGros.setRowCount(30)
        self.tblGros.setColumnCount(7)
        self.tblGros.setObjectName("tblGros")
        self.cmbMarke_4 = QtWidgets.QComboBox(self.centralwidget)
        self.cmbMarke_4.setGeometry(QtCore.QRect(700, -249, 91, 20))
        self.cmbMarke_4.setObjectName("cmbMarke_4")
        self.cmbMarke_5 = QtWidgets.QComboBox(self.centralwidget)
        self.cmbMarke_5.setGeometry(QtCore.QRect(926, -293, 91, 20))
        self.cmbMarke_5.setObjectName("cmbMarke_5")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 50, 261, 131))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lneLager = QtWidgets.QLineEdit(self.widget)
        self.lneLager.setText("")
        self.lneLager.setObjectName("lneLager")
        self.gridLayout.addWidget(self.lneLager, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lneName = QtWidgets.QLineEdit(self.widget)
        self.lneName.setObjectName("lneName")
        self.gridLayout.addWidget(self.lneName, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lneCode = QtWidgets.QLineEdit(self.widget)
        self.lneCode.setObjectName("lneCode")
        self.gridLayout.addWidget(self.lneCode, 0, 1, 1, 1)
        self.lnePreis = QtWidgets.QLineEdit(self.widget)
        self.lnePreis.setText("")
        self.lnePreis.setObjectName("lnePreis")
        self.gridLayout.addWidget(self.lnePreis, 2, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(310, 460, 741, 31))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnHinzufgen = QtWidgets.QPushButton(self.widget1)
        self.btnHinzufgen.setObjectName("btnHinzufgen")
        self.horizontalLayout.addWidget(self.btnHinzufgen)
        self.btnLoschen = QtWidgets.QPushButton(self.widget1)
        self.btnLoschen.setObjectName("btnLoschen")
        self.horizontalLayout.addWidget(self.btnLoschen)
        self.btnAktual = QtWidgets.QPushButton(self.widget1)
        self.btnAktual.setObjectName("btnAktual")
        self.horizontalLayout.addWidget(self.btnAktual)
        self.btnProduktListe = QtWidgets.QPushButton(self.widget1)
        self.btnProduktListe.setObjectName("btnProduktListe")
        self.horizontalLayout.addWidget(self.btnProduktListe)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(40, 400, 261, 51))
        self.widget2.setObjectName("widget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.widget2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 1)
        self.cmbMarke = QtWidgets.QComboBox(self.widget2)
        self.cmbMarke.setObjectName("cmbMarke")
        self.cmbMarke.addItem("")
        self.cmbMarke.addItem("")
        self.cmbMarke.addItem("")
        self.cmbMarke.addItem("")
        self.gridLayout_2.addWidget(self.cmbMarke, 1, 0, 1, 1)
        self.cmbKategorie = QtWidgets.QComboBox(self.widget2)
        self.cmbKategorie.setObjectName("cmbKategorie")
        self.cmbKategorie.addItem("")
        self.cmbKategorie.addItem("")
        self.cmbKategorie.addItem("")
        self.gridLayout_2.addWidget(self.cmbKategorie, 1, 1, 1, 1)
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(311, 21, 327, 25))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.widget3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.cmbNachKategorie = QtWidgets.QComboBox(self.widget3)
        self.cmbNachKategorie.setObjectName("cmbNachKategorie")
        self.cmbNachKategorie.addItem("")
        self.cmbNachKategorie.addItem("")
        self.cmbNachKategorie.addItem("")
        self.horizontalLayout_2.addWidget(self.cmbNachKategorie)
        self.btnNachKategorie = QtWidgets.QPushButton(self.widget3)
        self.btnNachKategorie.setObjectName("btnNachKategorie")
        self.horizontalLayout_2.addWidget(self.btnNachKategorie)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1110, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.cmbMarke.setCurrentIndex(-1)
        self.cmbKategorie.setCurrentIndex(-1)
        self.cmbNachKategorie.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Produktbeschreibung"))
        self.label_3.setText(_translate("MainWindow", "Produktstückpreis"))
        self.label_2.setText(_translate("MainWindow", "Produktname"))
        self.label_4.setText(_translate("MainWindow", "Produktlagermenge"))
        self.label.setText(_translate("MainWindow", "Produktcode"))
        self.btnHinzufgen.setText(_translate("MainWindow", "Produkt hinzufügen"))
        self.btnLoschen.setText(_translate("MainWindow", "Produkt löschen"))
        self.btnAktual.setText(_translate("MainWindow", "Produkt aktualisieren"))
        self.btnProduktListe.setText(_translate("MainWindow", "Produktliste"))
        self.label_6.setText(_translate("MainWindow", "Produktmarke"))
        self.label_7.setText(_translate("MainWindow", "Produktkategorie"))
        self.cmbMarke.setItemText(0, _translate("MainWindow", "Acer"))
        self.cmbMarke.setItemText(1, _translate("MainWindow", "Samsung"))
        self.cmbMarke.setItemText(2, _translate("MainWindow", "Apple"))
        self.cmbMarke.setItemText(3, _translate("MainWindow", "Oppo"))
        self.cmbKategorie.setItemText(0, _translate("MainWindow", "Telefon"))
        self.cmbKategorie.setItemText(1, _translate("MainWindow", "Computer"))
        self.cmbKategorie.setItemText(2, _translate("MainWindow", "Haushaltsgeräte"))
        self.label_8.setText(_translate("MainWindow", "Liste nach Kategorien"))
        self.cmbNachKategorie.setItemText(0, _translate("MainWindow", "Telefon"))
        self.cmbNachKategorie.setItemText(1, _translate("MainWindow", "Computer"))
        self.cmbNachKategorie.setItemText(2, _translate("MainWindow", "Haushaltsgeräte"))
        self.btnNachKategorie.setText(_translate("MainWindow", "Liste nach Kategorie"))

